export let APP = {
  HIDE_MODAL: 'APP/HIDE_MODAL'
}

export let AUTH = {
  LOGIN_SUCCESS: 'AUTH/LOGIN_SUCCESS',
  LOGOUT: 'AUTH/LOGOUT',
  SHOW_LOGIN_MODAL: 'AUTH/SHOW_LOGIN_MODAL'
}

export let DIALOGUE = {
  ADD: 'DIALOGUE/ADD',
  // COMPOSE: 'DIALOGUE/COMPOSE',
  FETCH: 'DIALOGUE/FETCH',
  FETCH_SUCCESS: 'DIALOGUE/FETCH_SUCCESS',
  ADD_STATEMENT: 'DIALOGUE/ADD_STATEMENT',
  UPDATE_DRAFT_STATEMENT: 'DIALOGUE/UPDATE_DRAFT_STATEMENT',
  UPDATE_NEW_DIALOGUE_TITLE: 'DIALOGUE/UPDATE_NEW_DIALOGUE_TITLE'
}

export let DIALOGUE_SUMMARY = {
  FETCH_ALL: 'DIALOGUE_SUMMARY/FETCH_ALL',
  FETCH_ALL_SUCCESS: 'DIALOGUE_SUMMARY/FETCH_ALL_SUCCESS'
}

export let LOCATION = {
  HOME: 'LOCATION/HOME',
  DIALOGUE: 'LOCATION/DIALOGUE',
  DIALOGUE_CREATOR: 'LOCATION/DIALOGUE_CREATOR'
}
